- name: playlevel variable
  hosts: local
  connection: local
  vars:
    Course: "DevOps with AWS"
    Duration: "2 Months"
    Trainer: "siva"
  tasks:
    - name: Print the variables
      ansible.builtin.debug:
        msg: "Course: {{ Course }}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"