- name: playlevel variable
  hosts: local
  connection: local
  var_files:
    - course.yml
    
  tasks:
    - name: Print the variables
      vars: 
        Course: Ansible
        Duration: 5 hours
        Trainer: siva kumar
      ansible.builtin.debug:
        msg: "Course: {{ Course }}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"