- name: demo on error handling
  hosts: local
  connection: local
  tasks:
    - name: check user exit or not 
      ansible.builtin.command: id roboshop
      register: user_check

    - name: print user check output
      ansible.builtin.debug:
        msg: "{{user_check}}"